name: cdth_mimic2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas < 2.0
  - pip
  - vega
  - altair
  - python-dateutil
  - nodejs
  - jupyterlab
  - ipywidgets
  - widgetsnbextension
  - markdown
